version: "3"
services:
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    container_name: ngircd
    volumes:
      - ngircd:/config
      - ./ngircd.conf:/config/ngircd.conf
      - ./ngircd.pem:/config/ngircd.pem
    restart: unless-stopped
    networks:
      - chat

  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    volumes:
      - thelounge:/var/opt/thelounge
      - ./thelounge.config.js:/var/opt/thelounge/config.js
      - ./ngircd.pem:/var/opt/thelounge/ngircd.pem
    networks:
      - chat

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.crt:/etc/nginx/nginx.crt
      - ./nginx.key:/etc/nginx/nginx.key
    networks:
      - chat


volumes:
  thelounge:
    name: thelounge
  ngircd:
    name: ngircd

networks:
  chat:
