name: PR Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write to file
        run: |
          echo "Hello, World!" > hello.txt
          if [ -s hello.txt ]; then
            echo "File created successfully"
          else
            echo "File creation failed" && exit 1
          fi

      - name: Check for Encrypted Files
        run: |
          find . -type f \( -iname "*.gpg" -o -iname "*.pgp" -o -iname "*.asc" -o -iname "*.kdbx" \) \( ! -path "./.git/*" ! -path "./.github/*" \) > encrypted_files.txt
          if [ -s encrypted_files.txt ]; then
            echo "Encrypted GPG files detected:" && cat encrypted_files.txt && exit 1
          fi
          find . -type f \( ! -path "./.git/*" ! -path "./.github/*" \) -exec file {} + | grep 'PGP message' > pgp_files.txt
          if [ -s pgp_files.txt ]; then
            echo "PGP encrypted files detected:" && cat pgp_files.txt && exit 1
          fi

      - name: Check for Compressed Files
        run: |
          find . -type f \( -iname "*.zip" -o -iname "*.tar.gz" -o -iname "*.tgz" -o -iname "*.rar" -o -iname "*.7z" -o -iname "*.bz2" -o -iname "*.xz" \) \( ! -path "./.git/*" ! -path "./.github/*" \) > compressed_files.txt
          if [ -s compressed_files.txt ]; then
            echo "Compressed files detected:" && cat compressed_files.txt && exit 1
          fi

      - name: Check Line and Character Limits
        run: |
          find . -type f \( ! -iname "*.pdf" ! -iname "*.doc" ! -iname "*.png" ! -iname "*.ppt" \) \( ! -path "./.git/*" ! -path "./.github/*" \) -print0 |
          xargs -0 awk 'length > 400 {print FILENAME " has a line exceeding 400 characters"; exit 1} END {if (NR > 15000) {print FILENAME " has more than 15,000 lines"; exit 1}}'

      - name: Check for Binary Files
        run: |
          find . -type f \( ! -path "./.git/*" ! -path "./.github/*" \) -exec file --mime {} + | grep -vE 'text|application/pdf|application/msword|image/png|application/vnd.ms-powerpoint' > binary_files.txt
          if [ -s binary_files.txt ]; then
            echo "Binary files detected:" && cat binary_files.txt && exit 1
          fi

      - name: Check README.md Content
        run: |
          find . -type d \( ! -iname ".git" ! -iname "*.github" \) -mindepth 1 -maxdepth 1 | while read dir; do
            if [ ! -s "$dir/school.md" ]; then
              echo "school.md is missing or empty in $dir" && exit 1
            fi
          done
